version: 2.1
defaults: &defaults
  working_directory: /tmp/persist_to_workspace
  machine:
      image: ubuntu-2004:202010-01

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: 
          name: build app
          command: |
            cd ./app
            npm install
            npm run build
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - .
          
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run: 
          name: teste de app
          command: |
            cd ./app
            npm run test
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - .

  trivy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run:
          name: Analise Trivy Docker 
          command: | 
            wget https://github.com/aquasecurity/trivy/releases/download/v0.30.2/trivy_0.30.2_Linux-64bit.deb
            sudo dpkg -i trivy_0.30.2_Linux-64bit.deb
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:0.18.3 ubuntu-2004:202010-01


  horusec:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run:
          name: Horusec Security Test
          command: |
            export HORUSEC_CLI_RETURN_ERROR_IF_FOUND_VULNERABILITY="false"
            export HORUSEC_CLI_ENABLE_OWASP_DEPENDENCY_CHECK="true"
            export HORUSEC_CLI_ENABLE_SHELLCHECK="true"
            curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
            horusec start -p="./app" --information-severity="false" -log-level="debug"
                        
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run:
          name: deploy para s3
          command: |
           aws s3 sync ./app/build s3://cicd-exemplo

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - trivy:
          requires:
            - test      
      - horusec:
          requires:
            - trivy
      - deploy:
          requires:
            - horusec
