version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: 
          name: build app
          command: |
            cd ./app
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
          
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: teste de app
          command: |
            cd ./app
            npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .

  horusec:
    machine:
       image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
       - run:
          name: Horusec Security Test
          command: |
            curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
            horusec start -p="./app" --disable-docker="true" --information-severity="true" -log-level="debug"
            
  deploy:
    machine:
        image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: deploy para s3
          command: |
           aws s3 sync ./app/build s3://cicd-exemplo

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - horusec:
          requires:
            - test
      - deploy:
          requires:
            - horusec
